language: python
python:
 - "3.6"
install:
 - pip install -U -i https://pypi.doubanio.com/simple pip setuptools wheel
 - pip install -U -i https://pypi.doubanio.com/simple pipenv
 - pip install coverage
 - pipenv install --deploy
script: nosetests --with-coverage --cover-package=flask_dantic_swagger
after_success:
  - coveralls
